---
title: "Solution Overview"
format: html
---
### Overview
The objective of this solution is to demonstrate AI for GRC solution that has the ability to streamline the GRC process and improve the overall efficiency of GRC workflow. To build an effective and efficient GRC system and achieve the desired outcomes for success, this solution will leverage watsonx Orchestrate to deliver these core capabilities:

1. [**Profile-based Data Querying**](/src/implementation_methodology/Profile-based%20Data%20Querying.qmd)
    - Answering questions on OpenPages Data Objects​
    - Answering questions on OpenPages Attachments​
1. [**AI-Augmented OpenPages Experience**](/src/implementation_methodology/AI-Augmented%20OpenPages%20Experience%E2%80%8B.qmd)
    - Automating Child Data Object Creation from Parent Data Object Entries
    - Realtime Similarity Identification for Data Objects
    - Executive Summary Creation
    - Categorization and Classification

### Technology Overview
- Core Platform: **IBM OpenPages** and **IBM watsonx Orchestrate** 
    - [**IBM OpenPages**](https://www.ibm.com/products/openpages)
    - [**IBM watsonx Orchestrate**](https://www.ibm.com/products/watsonx-orchestrate): IBM watsonx Orchestrate is a collaborative AI platform that automates workflows and manages complex business processes through seamless integration with enterprise systems which empowers users to streamline operations and boost productivity while enabling different capabilities like:
- Generative AI capabilities: [**IBM watsonx.ai platform**](https://www.ibm.com/products/watsonx-ai)

### User Journey
#### Current
#### Proposed